#ifndef __ScorchCrafter_C120__
#define __ScorchCrafter_C120__

#include <cmath>

#include "../common/sc_parameters.h"
#include "../common/custdata_types.h"
#include "../common/eq/lp_bworth.h"
#include "../common/sample_bank_fp.h"
#include "../common/dist/tube_bank_a.h"
#include "../common/eq/tonestack_a.h"

class SC_C120_Amp_Head
{
public:
	SC_C120_Amp_Head(double sRt = 44100.0);							//! Create an instance of the plug-in, setting a starting sample rate.  (Default is 44100 kHz.)
	~SC_C120_Amp_Head();

	void SetNewSampleRate(const double inp);							//! Use this whenever changing the standard sampling rate (NOT oversampling).
	void ClearAllBuffers();												//! Should be used when starting or stopping playback, or to silence effect "tail" tones.
																		//! Note:  This is automatically called when chagning certain other settings, such as sample rate, etc.,
																		//! So you do NOT need to call it when setting parameters, the plug-in will clear buffers as needed automatically in such cases.
	void SetFpParam(const int prm, float newValue);					//! Sets internal parameter (from the sc_parameters.h list) to a new 32-bit float value from 0.0f to 1.0f.
	void SetIntParam(const int prm, int newValue);					//! Sets internal parameter to new integer or boolean value, valid values can differ.
	void InputSample(const double inp);								//! Send an audio sample to the plugin (64-bit floating point).  Usually (but not always) should be from -1.0 to +1.0
	void InputSampleStereo(const double inpL, const double inpR);	//! Just like InputSample(), except for sending stereo sound to the plugin.
	void RunPlugin();													//! Always run this ONCE in the program loop for the plugin, to run all internals.  JUST ONCE, even when oversampling!
	double GetMonoOut();												//! Returns processed and/or generated audio of the plugin, in one mono channel.
	double GetStereoOutLeft();											//! Gets the LEFT channel audio output proecessed and/or generated by the plugin.
	double GetStereoOutRight();										//! Gets the RIGHT channel audio output proecessed and/or generated by the plugin.
	float GetFpParam(const int prm);									//! Returns 32-bit float internal value.  If the plugin doesn't have such a paramter, it returns 0.0f.
	int GetIntParam(const int prm);									//! Returns internal integer value.  If it is an invalid paramteter, it returns zero.
	long long GetLongParam(const int prm);							//! Returns internal integer value of great size.  If it is an invalid paramteter, it returns zero.  Not all plug-ins use this.

private:
	long fadeCount;					// Counts down and must be zero before audio is sent to the output.  Used to avoid pops and clicks.  Jumps up to the max when buffers are cleared or the plugin is reset.
	long fadeMax;					// This is the maximum for the fadecount, and is changed when the sample rate is updated.
	const double fadeFac;			// Determines how long the fade should be when buffers are cleared, this value can be different in various plugins but is fixed and does not change.
	double smpRate;				// Current sample rate that the plugin recognizes and runs at.
	double splInputMono;			// The input value the plug-in uses to preocess any audio from, 64-bit floating point.  Use the InputSample() function to pass audio in a stream to it.
	double splInputLeft;			// Same as splInputMono, except as the left channel of stereo input.
	double splInputRight;			// Same as splInputMono, except as the right channel of stereo input.
	double splOutputMono;			// Outyut audio sample after any processing, 64-bit floating point.  Use GetMonoOut() to retrieve its value.
	double splOutputLeft;			// Outyut audio sample after any processing, 64-bit floating point.  Use GetMonoOut() to retrieve its value.
	double splOutputRight;			// Outyut audio sample after any processing, 64-bit floating point.  Use GetMonoOut() to retrieve its value.

	float FpParam[ScPrmF_MAX_COUNT];
	int IntParam[ScPrmI_MAX_COUNT];

	Tube_BankA *PluGin;
	ToneStack_A *Qstack;

	fsx inputF_Pos;
	fsx inputF_Frq;
};

#endif
