#include <iostream>
#include <fstream>
#include <cmath>
#include <cstdlib>
#include <sstream>
#include <cstring>
// #define PRECISION_MAX
#include "../shared/custdata_types.h"

#define MAX_TSIZE_U 100000000
#define SHAPE_TABLE_SIZE 512

using namespace std;

double toDouble(const char *p)
{
  std::stringstream st (p);
  double r = double (0.0);
  st >> r;
  return double (r);
}

std::string toCstString(const double v)
{
	std::stringstream st;
	st << v;
	return st.str();
}

int main( int argc, const char* argv[] )
{
	double wavUp[SHAPE_TABLE_SIZE];
	double wavDn[SHAPE_TABLE_SIZE];
	f9x *tabU = new f9x[MAX_TSIZE_U];
	f9x *tabP = new f9x[SHAPE_TABLE_SIZE * 2];
	s9x markerEndUp = 0;
	s9x markerEndDn = 0;
	char fHeader[64] = "ScorchCrafter_Data_File\nOpen-Source_Audio_DAW_plug-in\n";
	int fVersionA = 1;
	int fVersionB = 0;
	int fVersionC = 0;
	char *fInfo = new char[64];
	fInfo = (char*)argv[2];

	double rWav[8192];

	if(argc < 3)
	{
		cout << "Usage: ShapeTool <input filename> <internal text description>\n";
		cout << "Input file must be one generated by ShapeWriter Plug-in\n";
		cout << "Future versions will load WAV files\n";

		return 0;
	}

	std::ifstream tf(argv[1], std::ios::in | std::ios::binary);
	if(!tf)
	{
		cout << "Error: Cannot load file.\n";

		return 1;
	}
	s9x i = 0;
	for(i = 0; i < 8192; i++)
	{
		tf.read((char*)&(rWav[i]), sizeof (double));
	}
	tf.close();

	cout << "Input File Loaded.\n";

	f9x maxVal = f9x (0.0);
	s9x startPoint = 0;
	s9x endPoint = 0;

	for(i = 0; i < 8192; i++)
	{
		if(double (rWav[i]) < double (0.0)) startPoint++;
		else break;
	}
	if(startPoint < 2)
	{
		cout << "Error: Cannot locate Start Point\n";
		return 1;
	}
	endPoint = startPoint;
	for (i = startPoint; i < 8192; i++)
	{
		if(double (rWav[i]) > double (0.0)) endPoint++;
		else break;
	}
	startPoint-=2;
	endPoint++;

	cout << "Raw start point is: " << startPoint << "\n";
	cout << "Raw end point is: " << endPoint << "\n";

	s9x iDx = 0;
	f9x fVal = f9x (0.0);
	f9x cVal = f9x (0.0);
	f9x vFac = f9x (f9x (1.0) / f9x ((MAX_TSIZE_U) - 1));
	f9x wEnd = f9x (s9x (endPoint - startPoint));
	s9x uDn = 0;
	for(iDx = 0; iDx < (MAX_TSIZE_U); iDx++)
	{
		cVal = f9x (f9x (iDx) * f9x (vFac) * f9x (wEnd));
		fVal = (f9x) floorl(f9x (cVal));
		cVal -= f9x (fVal);
		uDn = s9x (fVal);
		uDn += startPoint;
		tabU[iDx] = f9x (f9x (f9x (rWav[uDn]) * f9x (f9x (1.0) - f9x (cVal))) + f9x (f9x (rWav[uDn+1]) * f9x (cVal)));
	}
	s9x nStart = 0;
	s9x nEnd = 0;
	for(i = 0; i < MAX_TSIZE_U; i++)
	{
		if(f9x (tabU[i]) < f9x (0.0)) nStart++;
		else break;
	}
	nEnd = nStart;
	for(i = (nStart + 1); i < MAX_TSIZE_U; i++)
	{
		if(f9x (tabU[i]) > f9x (0.0)) nEnd++;
		else break;
	}

	s9x iLength = s9x (s9x (nEnd) - s9x (nStart));
	cout << "High-Precision Table Length is : " << iLength << "\n";
	s9x calcPos = 0;
	for(i = 0; i < (SHAPE_TABLE_SIZE * 2); i++)
	{
		calcPos = s9x (f9x (f9x (f9x (i) / f9x (s9x ((SHAPE_TABLE_SIZE * 2)-1))) * f9x (iLength)));
		tabP[i] = f9x (tabU[calcPos + nStart]);
	}

	cout << "Calibrating in preperation for normalization...\n";
	for(i = 0; i < (SHAPE_TABLE_SIZE * 2); i++)
	{
		if(f9x (tabP[i]) > f9x (maxVal)) maxVal = f9x (tabP[i]);
	}

	cout << "Normalizing...\n";
	for(i = 0; i < (SHAPE_TABLE_SIZE * 2); i++)
	{
		tabP[i] /= f9x (maxVal);
		tabP[i] = (f9x) sinl(f9x (f9x (tabP[i]) * f9x (0.50) * f9x (M_PI)));
	}

	for(i = 0; i < SHAPE_TABLE_SIZE; i++)
	{
		wavUp[i] = double (tabP[i]);
	}
	for(i = 0; i < (SHAPE_TABLE_SIZE); i++)
	{
		wavDn[i] = double (tabP[(SHAPE_TABLE_SIZE * 2) - (i+1)]);
	}

	cout << "\n";
	double fred = double (0.0);

	cout << "Upward .dat file: ";
	std::ofstream wrU("wavdat_up.dat", std::ios::out | std::ios::binary);
	for(i = 0; i < SHAPE_TABLE_SIZE; i++)
	{
		fred = (double) fabsl(double (wavUp[i]));
		wrU.write((char*)&fred, sizeof (double));
		// cout << "index " << i << " = " << s9x (double (double (fred) * LONG_LONG_MAX)) << "\n";
	}
	wrU.close();
	cout << "Done!\n";

	cout << "Downward .dat file: ";
	std::ofstream wrD("wavdat_dn.dat", std::ios::out | std::ios::binary);
	for(i = 0; i < SHAPE_TABLE_SIZE; i++)
	{
		fred = (double) fabsl(double (wavDn[i]));
		wrD.write((char*)&fred, sizeof (double));
		// cout << "index " << i << " = " << s9x (double (double (fred) * LONG_LONG_MAX)) << "\n";
	}
	wrD.close();
	cout << "Done!\n";

	cout << "\n";

	char xFChar[16];
	int j = 0;

	cout << "Upward .h file: ";
	std::ofstream tfileU;
	tfileU.open("w_dat_up.h");
	tfileU << "char wavdatUp[] = {";
	for(i = 0; i < SHAPE_TABLE_SIZE; i++)
	{
		fred = (double) fabsl(double (wavUp[i]));
		ostringstream xFStr;
		xFStr << fred;
		strncpy(xFChar, xFStr.str().c_str(), sizeof (double));
		for(j = 0; j < sizeof (double); j++)
		{
			tfileU << int (xFChar[j]) << ",";
		}
		tfileU << "\n";
	}
	tfileU << "}; \n";
	tfileU.close();
	cout << "Done!\n";

	cout << "Downward .h file: ";
	std::ofstream tfileD;
	tfileD.open("w_dat_dn.h");
	tfileD << "char wavdatDn[] = {";
	for(i = 0; i < SHAPE_TABLE_SIZE; i++)
	{
		fred = (double) fabsl(double (wavDn[i]));
		ostringstream xFStr;
		xFStr << fred;
		strncpy(xFChar, xFStr.str().c_str(), sizeof (double));
		for(j = 0; j < sizeof (double); j++)
		{
			tfileD << int (xFChar[j]) << ",";
		}
		tfileD << "\n";
	}
	tfileD << "}; \n";
	tfileD.close();
	cout << "Done!\n";

	cout << "\n";

	return 0;
}
